### ISSUE TITLE
json: cannot unmarshal string into Go struct field KinesisFirehoseEventRecord.approximateArrivalTimestamp of type int64

### ISSUE THREAD

**Issue by natsumehu** [aws/aws-lambda-go#101]
It seems like the firehose is passing a ISO 8601 date formate instead of a long number to the lambda function. But the go sdk cannot parse it? Any idea?

**Comment by bmoffatt** [comment]
@natsumehu were you using the sample Kinesis Firehose event template in the Lambda Console? This sample was recently corrected to reflect that `"approximateArrivalTimestamp"` is an integer.

**Comment by bhavikkumar** [comment]
I think this has been fixed by multiple PRs one being https://github.com/aws/aws-lambda-go/pull/188
