### ISSUE TITLE
PR for SQS event handler 

### ISSUE THREAD

**Issue by os2tux** [aws/aws-lambda-go#109]
I created a local struct and handler for SQS events received by Lambda. I didn't see a PR or open issue for this and wanted to see if I might submit what I've created for review and inclusion in the SDK. Thanks!

**Comment by os2tux** [comment]
Harrison:

Apologies for the delayed response; things got a bit hectic with work last week. What I created is something different. Specifically, it’s a struct for the SQS event delivered via Lambda. This is similar to the other structs already present in the /events package.

I know this integration only became available very recently, which is why I figured it wasn’t already in the SDK.

I can confirm that I’m okay to distribute the code to the project (given that it was developed for work), which I’m sure won’t be an issue, if you’d like to take a look.

Thanks!

Respectfully,

Joseph Shelby

Sr. DevOps Engineer, ETS/Platform Architecture
zoom: https://asurion.zoom.us/my/josephshelby | slack: @jcshelby
voice: 615.445.1240 | mobile: 615.210.6139
mail: Asurion I 648 Grassmere Park, Nashville, TN 37211
www.asurion.com<http://www.asurion.com/> I Twitter<https://twitter.com/Asurion> I Facebook<https://www.facebook.com/Asurion>

**Comment by bmoffatt** [comment]
@harrisonhjones is correct. SQS events received by Lambda functions are modeled by https://github.com/aws/aws-lambda-go/blob/master/events/sqs.go 

@os2tux you're welcome to post a pull-request is this event type has missed something, or to make other event model contributions.
