### ISSUE TITLE
Missing notifcationType in SimpleEmailService

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-lambda-go#118]
https://github.com/aws/aws-lambda-go/blob/master/events/ses.go#L16

Put https://s.natalian.org/2018-09-13/ses.json into https://mholt.github.io/json-to-go/

**Comment by kaihendry** [comment]
Furthermore https://github.com/aws/aws-lambda-go/blob/master/events/ses.go#L58-L62 is missing details like topicArn, bucketName, objectKey et al

**Comment by bmoffatt** [comment]
resolved by #211
