### ISSUE TITLE
lambdacontext missing definitions of authorizer value?

### ISSUE THREAD

**Issue by mykter** [aws/aws-lambda-go#124]
In other languages when using a UserPool authorizer (or a lambda authorizer), the context object includes an `authorizer` value. You can use this to inspect attributes about the user such as groups - here's [a python example](https://www.reddit.com/r/aws/comments/8ym08a/cognito_separating_users_into_user_pools_or_into/e2c3k4z).

I presume this is also theoretically possible in go, but the [lambdacontext](https://github.com/aws/aws-lambda-go/blob/master/lambdacontext/context.go) doesn't have the type definitions for authorizer. Unlike in python or javascript, it's not easy to dump the values from a context object without the type specification.

 - Is the extra authorizer information included in the context object in go lambda functions?
 - If so, how can we get access to it?
 - If not, is there another means of obtaining this information, or is it just not supported for Go?

**Comment by bmoffatt** [comment]
$context in API Gateway's documentation doesn't refer to values passed with `lambdacontext`. If you're using the API Gateway proxy integration with Lambda, the API Gateway `$context` values are passed with the event body. https://github.com/aws/aws-lambda-go/blob/master/events/apigw.go#L36

**Comment by Nikita-T86** [comment]
For dummies like me who came to this page by googling how to use Lambda authorizer context in other Lambdas in API Gateway. If using Lambda proxy, the context of Lambda authorizer is in event["requestContext"]["authorizer"], i.e. in Python:

def lambda_handler(event, context):
      username = event["requestContext"]["authorizer"]["username"]

**Comment by mattgrannary** [comment]
It seems that the authorizer context is only passed to your lambda when apigateway is directly invoking it. I have a situation where I have an application load balancer between apigateway and my lambda via an integration so my handler needs to accept the `events.ALBTargetGroupRequest` typed event.

The ALB *should* be proxying the request from apigateway but the `RequestContext` only includes `ELB.TargetGroupArn`. The [lambda docs](https://docs.aws.amazon.com/lambda/latest/dg/services-alb.html) don't mention anything about apigateway authorizer context. They do say that along with the body there should be some metadata but I only receive the raw body string.

Does anyone know how I can get the authorizer context to be passed on to my handler?

**Comment by mattgrannary** [comment]
I figured it out. I needed to add a parameter mapping on my integration to convert the context parameter value to a header. The context params can be accessed from `$context.authorizer.{property}`.
