### ISSUE TITLE
cannot unmarshal string into Go struct field SimpleEmailReceipt.dmarcPolicy of type events.SimpleEmailVerdict

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-lambda-go#126]
Workaround was to:

    DMARCPolicy          json.RawMessage          `json:"dmarcPolicy"`

https://github.com/aws/aws-lambda-go/blob/master/events/ses.go#L37

These poor mappings are making it really quite painful to develop with Golang and AWS... Else am I missing a trick?

**Comment by bmoffatt** [comment]
looks like same test sample included #102 doesn't match the docs description. 

https://docs.aws.amazon.com/ses/latest/DeveloperGuide/receiving-email-notifications-contents.html#receiving-email-notifications-contents-receipt-object
> Possible values for this field are:
>
>   none: The owner of the sending domain requests that no specific action be taken on messages that fail DMARC authentication.
>
>    quarantine: The owner of the sending domain requests that messages that fail DMARC authentication be treated by receivers as suspicious.
>
 >   reject: The owner of the sending domain requests that messages that fail DMARC authentication be rejected.

Until a fix is pushed, you can continue using your patch, or use the v1.4.0 tag

**Comment by bmoffatt** [comment]
merged #165
