### ISSUE TITLE
Deployment .zip file permissions

### ISSUE THREAD

**Issue by moitias** [aws/aws-lambda-go#13]
I'm developing on Windows, and while Go allows for very easy cross-compilation, deployment is not as easy as it is shown currently in the blog. 

Namely, the problem is that on Windows (even with Cygwin zip) it seems rather difficult to create a .zip that would work when uploaded to Lambda, resulting in the rather terse error:
```
fork/exec /var/task/handler.lambda: permission denied: PathError
null
```

I believe this is due to it being difficult to set the executable flag that gets embedded into the .zip file. With the flag missing, when Lambda unpacks the binary the result is a non-executable binary that gives out the error above, while no warning is raised while uploading.

Taking the exact same output (built on Windows) and chmod +x:ing in Linux and then zipping it results in a working Lambda function, as expected. 

I'm not sure what the correct way to approach fixing this would be, but I would suggest going by Postel's robustness principle and being liberal in what to accept - eg. forcing the executable flag on after the handler is unpacked. This is especially because the permissions in .zip files is a rather complex issue and executable flags certainly are not at all familiar to developers on Windows, so it seems to me to be a pretty big stumbling block for a sizable share of developers.

For posterity, I triaged this by copying the required flags from the correct zip to add the required flags with archive/zip; the flags that resulted in a working .zip are;

```
fh := &zip.FileHeader{
	Name: "handler.lambda",
}
fh.CreatorVersion = 0x31e
fh.Flags = 0
fh.Extra = []uint8{0x55, 0x54, 0x5, 0x0, 0x3, 0x9d, 0x33, 0x5f, 0x5a, 0x75, 0x78, 0xb, 0x0, 0x1, 0x4, 0xe8, 0x3, 0x0, 0x0, 0x4, 0xe8, 0x3, 0x0, 0x0}
fh.ExternalAttrs = 0x81ed0000
```

**Comment by bmoffatt** [comment]
Thanks for opening this issue. Others have been hitting this problem, and we're working getting a minimal workaround into the official documentation.

In the snippet you included, the `ExternalAttrs` and `CreatorVersion` is where the magic is. Setting it to `ExternalAttrs = (0777 << 16)` makes the permissions clear. And setting CreatorVersion to `(3 << 8)` - [indicating unix](https://github.com/golang/go/blob/67fdf587dc5c3ac9f6891c9502d5cfdd1234a37e/src/archive/zip/struct.go#L51) - was sufficient for me to create a working zip file.

**Comment by dlsniper** [comment]
Alternatively, create the zip from WSL (Windows Subsystem for Linux, Bash on Linux on Windows), and the binary will always have the executable bit (as will any other file).

**Comment by bmoffatt** [comment]
I have added a small tool that can create .zip files containing the handler executable such that it is usable on Lambda. I hope this helps lower the barrier for developing on Windows. Be sure to let us know about any other pain points you come across!

**Comment by austink-carb** [comment]
Hi. I'm noticing that when I zip with `build-lambda-zip`, all files after the first in the zip are getting the original error "permission denied; path error"

Any ideas?

**Comment by rh-galaxy** [comment]
Use my windows command line utility [zip_exec.zip][1] to set the executable flag for linux/unix and mac (tested on files created with Windows explorer and 7zip). The cpp [source][2] is also available.

  [1]: http://www.galaxy-forces.com/zip_exec.zip
  [2]: https://sourceforge.net/p/galaxyv2/code/HEAD/tree/other/zip_exec/
