### ISSUE TITLE
handle IOT events with raw payload

### ISSUE THREAD

**Issue by dschnabel** [aws/aws-lambda-go#147]
Is it possible to receive IOT events with raw payload? I am able to receive events with JSON payload but in my use case I want to process IOT messages that contain a raw (binary payload) which doesn't seem possible now?

If I use `[]byte` for the event type instead of a JSON struct, I'm getting this error message:
```
json: cannot unmarshal object into Go value of type []uint8: UnmarshalTypeError
```
---
To clarify, this works:
```
type IoTEvent struct {
    A   string `json:"a"`
    B   string `json:"b"`
}
func router(ctx context.Context, event IoTEvent) { ... }
```
And this doesn't work:
```
func router(ctx context.Context, event []byte) { ... }
```

**Comment by dschnabel** [comment]
Got it to work by using this SELECT rule: `SELECT encode(*, 'base64') AS a FROM 'my-topic'`

This will encode the raw payload as base64 which then is accessible in lambda as `event.A`.

Closing.

**Comment by Marcelo-Rodriguez-Teracode** [comment]
Hi @dschnabel , could you provide an example code , please ! Im really new on this and Im facing the same problem . Thanks in advance !

**Comment by dschnabel** [comment]
@Marcelo-Rodriguez-Teracode 
Is [this](https://github.com/dschnabel/ArduinoProject/blob/master/aws/lambda/agent/main.go#L134) helpful?
