### ISSUE TITLE
Drop-in replacement for net/http

### ISSUE THREAD

**Issue by tj** [aws/aws-lambda-go#15]
Any thoughts on having something like https://github.com/apex/gateway in here to act as a drop-in replacement for net/http? Happy to add some tests/refine (probably missing some stuff too) and send a pull-request.

May also be worth discussing the best way to pass the contextual information for this kind of scenario, maybe `X-Something-Context: json here` or more distinct fields?

**Comment by jadbox** [comment]
@wolfeidau It looks like that project is a kind of proxy to the go runtime. For performance sake, I'd still want a native net/http wrapper to use, as there's a high performance cost whenever you introduce software proxies (esp L7 proxies).

**Comment by bmoffatt** [comment]
For now, I want to be conservative about what gets added to this repo. I also agree that a convenience wrapper for the api gateway proxy integration makes sense as a standalone library.

> May also be worth discussing the best way to pass the contextual information for this kind of scenario

`X-Aws-Lambda-Context: <json>` looks about right to me. For an net/http standin, you may also want to copy `ctx.Value("x-amzn-trace-id")` as `X-Amzn-Trace-Id` for users of https://github.com/aws/aws-xray-sdk-go

**Comment by mrmark** [comment]
Thanks for the feedback!
> I also think that a convenience wrapper for the api gateway proxy integration makes sense as a standalone library.

Are you thinking this would be a new repo under `aws/` or 100% community driven and live in `apex` and friends?

**Comment by tj** [comment]
@bmoffatt yea that's totally reasonable, figured it was worth a shot :D

**Comment by imdario** [comment]
As a developer of another drop-in replacement, [imdario/gluo](https://github.com/imdario/gluo), close to apex/gateway, I also agree makes sense as a standalone library.

**Comment by tj** [comment]
hahah so many of these now :D
