### ISSUE TITLE
json: cannot unmarshal string into Go struct field APIGatewayProxyRequestContext.authorizer

### ISSUE THREAD

**Issue by Yenchu** [aws/aws-lambda-go#154]
When integrating with api gateway WebSocket API, got error in CloudWatch log:
`
json: cannot unmarshal string into Go struct field APIGatewayProxyRequestContext.authorizer of type map[string]interface {}: UnmarshalTypeError null
`

To log requestContext info, the field **authorizer** is empty:
`
requestContext:map[stage:... authorizer: messageId:<nil>...
`

**Comment by piotrkubisa** [comment]
The type definition is a bit different for a Websocket events - for an instance (I might don't recall correctly) there are at least two fields which are missing in the `requestContext`:

```ts
connectionId: string
connectedAt: number
```

https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-logging.html

That said, `aws-lambda-go` repository lacks with the struct for an API Gateway usage with a websocket. It would be great if someone could copy and paste the raw event payload here or make an PR and add it into the test data directory and create new struct with a corresponding `json` tags definition.

**Comment by Dasio** [comment]
These are extra fields in APIGatewayProxyRequestContext
```go
	ConnectedAt        int64       `json:"connectedAt"`
	ConnectionID       string      `json:"connectionId"`
	DomainName         string      `json:"domainName"`
	Error              string      `json:"error"`
	EventType          string      `json:"eventType"`
	ExtendedRequestId  string      `json:"extendedRequestId"`
	IntegrationLatency string      `json:"integrationLatency"`
	MessageDirection   string      `json:"messageDirection"`
	// IDK type of this
	MessageID          interface{} `json:"messageId"`
	RequestTime        string      `json:"requestTime"`
	RequestTimeEpoch   int64       `json:"requestTime"`
	RouteKey           string      `json:"routeKey"`
	Status             string      `json:"status"`
```
But in WS event it is
```go
	Authorizer   string                      `json:"authorizer"`
```
Now it's 
```go
	Authorizer   map[string]interface{}    `json:"authorizer"`
```

**Comment by jozanza** [comment]
Just chiming in here -- I forked and deployed to aws with the code from #159, and it seems that if you do not set an authorizer on your WebSocket route in API Gateway, the marshalling of `APIGatewayWebsocketProxyRequest` will still fail since it's not able to convert `null` to `map[string]interface{}`. Entirely removing the `Authorizer` field from the struct worked, but that's probably not the best option 😅 .

**Comment by bmoffatt** [comment]
`Authorizer` is going to have to be an `interface{}` to be compatible with all the different ways it can be populated
