### ISSUE TITLE
Missing NewNewNumberSetAttribute method in events/attributevalue.go

### ISSUE THREAD

**Issue by alexbilbie** [aws/aws-lambda-go#157]
The file `events/attributevalue.go` defines the following DynamoDB data types:

```
DataTypeBinary
DataTypeBoolean
DataTypeBinarySet
DataTypeList
DataTypeMap
DataTypeNumber
DataTypeNumberSet
DataTypeNull
DataTypeString
DataTypeStringSet
```

All of these data types have a constructor method - e.g. `NewStringAttribute` - except `DataTypeNumberSet`.

Can I propose the method `NewNumberSetAttribute` be added?

**Comment by bmoffatt** [comment]
👍 Yes, there should be a constructor added for the NumberSet type.
