### ISSUE TITLE
CloudFormation wrapper should recover from panics

### ISSUE THREAD

**Issue by aidansteele** [aws/aws-lambda-go#172]
https://github.com/aws/aws-lambda-go/blob/ec2fec7cfe48fbf48ea1a6855a077c372bbb1b1c/cfn/wrap.go#L14

If a `CustomResourceLambdaFunction` (definition above) panics, it is recovered from in the generic Lambda handling below:

https://github.com/aws/aws-lambda-go/blob/02a038f1708ade8d5fd6a28ee309c388008fe770/lambda/function.go#L26-L34

This will cause stack creations/updates to hang for a long time, as CloudFormation has a very long timeout waiting for a response. It would be a significant improvement if the custom resource wrapper recovered from panics and sent the error to the CloudFormation service.

Is this something you would be open to? I would be happy to submit a PR for review if you are ok with the idea.

**Comment by bmoffatt** [comment]
Sounds like a good idea to me!
