### ISSUE TITLE
Travis CI builds for modern versions of Go

### ISSUE THREAD

**Issue by greggjs** [aws/aws-lambda-go#175]
Currently there's only builds that pass for go 1.9, in which I do not even know what version of go 1.9 it even supports. I would think it'd be reasonable to have Travis jobs spin up for every modern version of Go (including 1.10, 1.11, and 1.12) because normal people like to keep up to date with their software and not stay on old versions that have security bugs.

**Comment by bmoffatt** [comment]
done!

**Comment by greggjs** [comment]
Wow so quick! Thanks for the promptness!
