### ISSUE TITLE
Go equivalent of Java's RequestStreamHandler

### ISSUE THREAD

**Issue by dmolesUC** [aws/aws-lambda-go#195]
**Is your feature request related to a problem? Please describe.**

I would like to be able to write lambda functions in Go that process and return more data than can easily fit in RAM, e.g. transformations on / aggregations of large S3 objects.

**Describe the solution you'd like**

An `io.Reader` and/or `io.Writer`-based `Handler` alternative that allows me to write to a stream rather than fit my response in a byte slice.

**Describe alternatives you've considered**

1. I can write the data to intermediate storage in an S3 bucket and return the location of the S3 object, but that adds overhead and complexity, and incurs storage and access costs.
2. I can write a web app instead of a lambda and deploy it in a container using Elastic Beanstalk, but that adds various kinds of complexity I was hoping to avoid.
3. I can use a different language, such as Java or C#, that supports streams, but if I was happy programming in Java or C# I wouldn't be writing Go programs.

**Comment by bmoffatt** [comment]
Setting expectations: Adding the proposed streaming interface may not enable your use-case if you're dealing with large-enough S3 objects. Lambda function responses are limited to 6 MB. The C# and Java "streaming" interfaces do not enable these runtimes to exceed the 6 MB response size limit.

https://docs.aws.amazon.com/lambda/latest/dg/limits.html.

**Comment by dmolesUC3** [comment]
OK, so Lambda probably isn't the right tool for my use case; good to know. Still nice to have in terms of feature parity across languages, but.

**Comment by abhisekp-impeller** [comment]
Is there any example of using response stream with lamdba?
I'm trying to respond with a binary response stream of PDF - small size.

**Comment by bmoffatt** [comment]
The best answer today probably depends on the client calling the function
1. API Gateway
2. Lambda Function URLs
3. direct invoke via an AWS SDK

1 & 2 have response structs in the `events` package that support the response data being a base64 encoded string. This then will appear as the decoded binary data to the end client.

2 & 3 support returning a byte slice as-is, but the way to implement the handler has a bit of boilerplate. See https://pkg.go.dev/github.com/aws/aws-lambda-go@v1.34.1/lambda#StartHandler - this support was added in https://github.com/aws/aws-lambda-go/pull/69

**Comment by bmoffatt** [comment]
Implemented by #472
