### ISSUE TITLE
Invalid API Gateway Response Keys

### ISSUE THREAD

**Issue by wiliamsouza** [aws/aws-lambda-go#198]
This PR https://github.com/awslabs/aws-sam-cli/pull/1154 released with aws-sam-cli version v0.16.0 do not allow `multiValueHeaders` from `APIGatewayProxyResponse` https://github.com/aws/aws-lambda-go/blob/master/events/apigw.go#L25 

`multiValueHeaders` was added in this PR https://github.com/aws/aws-lambda-go/pull/155

**Comment by bmoffatt** [comment]
This should be fixed by https://github.com/awslabs/aws-sam-cli/pull/1166. Until a new release is made, you can downgrade to v0.15.0 per https://github.com/awslabs/aws-sam-cli/issues/1190

**Comment by bmoffatt** [comment]
Fixed by https://github.com/awslabs/aws-sam-cli/releases/tag/v0.17.0
