### ISSUE TITLE
Invoke api gateway function locally

### ISSUE THREAD

**Issue by terrywarwar** [aws/aws-lambda-go#2]
How do you Invoke a api gateway event function locally to see results?

**Comment by roryj** [comment]
Hi @terrywarwar, I recommend you look at [Sam Local](https://github.com/awslabs/aws-sam-local) which does exactly that. There is currently not support for go-lang, but it is definitely on our short term roadmap, so I would watch that repo for updates.

**Comment by terrywarwar** [comment]
thanks @roryj.
