### ISSUE TITLE
Event for CloudWatch scheduled function execution

### ISSUE THREAD

**Issue by ravernkoh** [aws/aws-lambda-go#20]
Looking for the equivalent of [this](https://github.com/apex/apex-go/blob/master/cloudwatch/cloudwatch.go), which is an struct mapping for a CloudWatch scheduled function execution event.

Am I completely missing something here?

**Comment by mpgerlek** [comment]
+1

**Comment by binary132** [comment]
Same

**Comment by bmoffatt** [comment]
merged 5fea2b254568d4043f23d27471ae265cd33d3530
