### ISSUE TITLE
Calling fmt.Printf("%v") on a DynamoDBAttributeValue causes mini-panic

### ISSUE THREAD

**Issue by keyneston** [aws/aws-lambda-go#205]
When you call `fmt.Printf("%v")` on any non-String `events.DynamoDBAttributeValue` a panic gets embedded into your string.

Example:
```golang
package main

import (
	"fmt"

	"github.com/aws/aws-lambda-go/events"
)

func main() {
	v := events.NewNumberAttribute("5")
	fmt.Println("This is a number: %v", v)
}
```

Outputs:

```
$ go run bugreport.go
This is a number: %v %!v(PANIC=String method: accessor called for incompatible type, requested type 8 but actual type was 5)
```

As far as I can tell this is due to the fact that you are using `.String()` as the function to get back a string from the attribute. This conflicts with the fact that `.String()` is also the interface used for printing. https://github.com/aws/aws-lambda-go/blob/ec2fec7cfe48fbf48ea1a6855a077c372bbb1b1c/events/attributevalue.go#L94

**Comment by bmoffatt** [comment]
Merged #226
