### ISSUE TITLE
I need to include some files such as json file as a part of Lambda Zip package

### ISSUE THREAD

**Issue by VigneshSonaiya** [aws/aws-lambda-go#206]
I'm trying to read some file through my Lambda using go. It's working in local when I put that into Lambda it's not working. I got error like "no such file or directory". How to include in other files as part of go Lambda Zip package?

**Comment by bmoffatt** [comment]
How are you constructing your zip file? If you're using MacOS or Linux, you can add multiple files with the `zip` command

```
GOOS=linux GOARCH=amd64 go build -o main main.go

zip main.zip main my-cool-config.json configuration/other-cool-config.json
```

**Comment by VigneshSonaiya** [comment]
Thank you. :)

**Comment by duanju** [comment]
How to achieve this when using SAM(Serverless Application Model)?
