### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by karthikeyand14** [aws/aws-lambda-go#216]
I am trying to install from command prompt. Below is the command.
go get github.com/aws/aws-lambda-go/cmd/build-lambda-zip

Receiving the below error.
"package gopkg.in/urfave/cli.v1: unrecognized import path "gopkg.in/urfave/cli.v1" (https fetch: Get https://gopkg.in/urfave/cli.v1?go-get=1: authenticationrequired)"

Tried installing "go get gopkg.in/urfave/cli.v1"
Received below error "package gopkg.in/urfave/cli.v1: unrecognized import path "gopkg.in/urfave/cli.v1" (https fetch: Get https://gopkg.in/urfave/cli.v1?go-get=1: authenticationrequired)"

**Comment by karthikeyand14** [comment]
Need help in resolving this issue

**Comment by bmoffatt** [comment]
I believe this was resolved by #223.
