### ISSUE TITLE
Cannot erase AWS Lex SessionAttributes

### ISSUE THREAD

**Issue by artempanko** [aws/aws-lambda-go#218]
For erasing aws lex sessionAttributes I need to pass empty map according to aws lex docs (https://docs.aws.amazon.com/lex/latest/dg/context-mgmt.html)
But `LexResponse` uses json tag with `omitempty` option and aws lex won't clear sessionAttributes.
Code example: https://play.golang.org/p/Qpca-uHwGQL
I'm proposing to remove `omitempty` option in `LexResponse` struct.

**Comment by bmoffatt** [comment]
Makes sense to me, feel free to open a pull-request!

**Comment by artempanko** [comment]
Hi, I've created, please review https://github.com/aws/aws-lambda-go/pull/225
