### ISSUE TITLE
Custom CloudFormation resources should gracefully handle stack creation rollbacks

### ISSUE THREAD

**Issue by BalmanRawat** [aws/aws-lambda-go#237]
**Is your feature request related to a problem? Please describe.**
Whenever a lambda backed custom resource creation fails, "github.com/aws/aws-lambda-go/cfn" returns a **physicalResourceID** to CloudFormation which doesn't exist. Then when CloudFormation tries to DELETE non-existent resource it fails. I have to manually skip the deletion of that particular custom resource to delete the Stack.

**Describe the solution you'd like**
Custom CloudFormation Resource should be able to be deleted like other normal Resources even though the CREATE event was not successful

**Additional context**

####### Here My Custom Resource is returning some ID when failed to create
<img width="906" alt="Screen Shot 2019-09-24 at 11 24 34 AM" src="https://user-images.githubusercontent.com/8892649/65484243-851e0380-debe-11e9-8c62-553779cb9f92.png">

####### Here AWS Security Group returning nothing when failed to create

<img width="906" alt="Screen Shot 2019-09-24 at 11 29 49 AM" src="https://user-images.githubusercontent.com/8892649/65484498-f1990280-debe-11e9-9199-484e2a60c013.png">

###### Related PR
https://github.com/remind101/empire/issues/918

**Comment by leepa** [comment]
See #107 as that's why it was added.  I didn't add it originally because of this though - removing it again or at least reverting #108 might be the sensible thing here.

**Comment by bmoffatt** [comment]
reverting #108 makes sense to me. We'll have to re-open #107 to solve the error-masking problem originally described there.
