### ISSUE TITLE
Missing flag?

### ISSUE THREAD

**Issue by jonathangiber** [aws/aws-lambda-go#250]
Hi,
I'm getting this error since the last PR that was merged:

#!/bin/bash -eo pipefail
build-lambda-zip -o ${LAMBDA_FUNCTION_BINARY_ZIP} ${LAMBDA_FUNCTION_BINARY}
Incorrect Usage. flag provided but not defined: -o

NAME:
   build-lambda-zip - Put an executable and supplemental files into a zip file that works with AWS Lambda.

USAGE:
   build-lambda-zip [global options] command [command options] [arguments...]

VERSION:
   0.0.0

COMMANDS:
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --output value  output file path for the zip. Defaults to the first input file name.
   --help, -h      show help (default: false)
   --version, -v   print the version (default: false)
flag provided but not defined: -o
Exited with code 1

**Comment by diegobernardes** [comment]
Hi @jonathangiber seems like your `build-lambda-go` was not updated.

From your output, the value ` --output value output file path for the zip. Defaults to the first input file name. ` should be like this `   --output value, -o value  output file path for the zip. Defaults to the first input file name.`.

**Comment by jonathangiber** [comment]
Changing -o for --output solved it, thanks

**Comment by bmoffatt** [comment]
`-o` should still work. The problem is that `go get` is pulling master fir urfave/cli, which was recently merged with their v2 branch.

To ensure build-lambda-zip is build with the right version of its dependency, try installing it with `GO111MODULE=on go get -u github.com/bmoffatt/aws-lambda-go/cmd/build-lambda-zip`
