### ISSUE TITLE
Missing `clientMetadata` field in CognitoEventUserPoolsPostConfirmationResponse

### ISSUE THREAD

**Issue by thepelkus-too** [aws/aws-lambda-go#255]
According to the documentation at https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-post-confirmation.html, there should be a clientMetadata field on the request for the Post Confirmation Lambda Trigger. However, in the types in https://github.com/aws/aws-lambda-go/blob/master/events/cognito.go, there is no clientMetadata field on the corresponding type. When I add that field and deploy, I see that I'm able to access that data when it's passed in a request.

I'm down to open a little PR to add this, but I wanted to make sure it had the green light from project maintainers first. 😄

**Comment by bmoffatt** [comment]
Feel free to open a PR!
