### ISSUE TITLE
How is _LAMBDA_SERVER_PORT invoked inside of Lambda?

### ISSUE THREAD

**Issue by cheld** [aws/aws-lambda-go#257]
Hello,

I am trying to understand how Lambda for Go actually works. In case of custom runtime the event must be retrieved from the following endpoint:

http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next

I assume that also in case of Golang the Lambda runtime retrieves the event from the upper endpoint and then forwards to _LAMBDA_SERVER_PORT. Is this correct? Or ist the endpoint used directly to push the event from something like sns?

Thanks

**Comment by mhart** [comment]
@cheld that's only for custom runtimes. The Go runtime predates that mechanism and uses its own RPC mechanism

**Comment by cheld** [comment]
Thanks
