### ISSUE TITLE
30 lambdas --> 30 mains?

### ISSUE THREAD

**Issue by mpgerlek** [aws/aws-lambda-go#26]
I feel I must be missing something really obvious, so I want to check my understanding of the requirement to provide a `main` entry point for my lambda:

```func main() { lambda.Start(MyLamb) }```

For my serverless application, which happens to have 30 lambdas, do I really need to build 30 individual binaries and put them each into one big zip file to be uploaded (or, alternatively, 30 little zip files)?

**Comment by bmoffatt** [comment]
Lambda uses the `handler` as the name of the executable to run. 

From https://docs.aws.amazon.com/lambda/latest/dg/best-practices.html#function-code
> Minimize your deployment package size to its runtime necessities. This will reduce the amount of time that it takes for your deployment package to be downloaded and unpacked ahead of invocation. 

For your application, 30 binaries and 30 zips should improve you worst case cold start time.

However, if it makes sense for your application, you can a single handler, that switches on some part of your event body. here is a complete example of this pattern in node.js https://github.com/awslabs/aws-serverless-crud-sample

**Comment by deluan** [comment]
Currently I have one main (only one executable) for 4 different lambdas and I use the `lambdacontext.FunctionName` to determine which function to invoke

**Comment by benkraus** [comment]
There is also [this](https://github.com/mthenw/serverless-golang-template) example using the Serverless framework. It essentially uses a Makefile to build all the bins, and the Serverless framework handles linking each route to each individual bin. It's the cleanest solution I have seen so far.
