### ISSUE TITLE
AWS API Gateway now supports multi-value parameters but APIGatewayProxyRequest doesn't

### ISSUE THREAD

**Issue by beaubrewer** [aws/aws-lambda-go#262]
Go's standard http.Request has a Query() accessor that returns a map[string][]string (https://github.com/golang/go/blob/master/src/net/url/url.go#L828). This supports requests with multiple query params of the same key name ...?name=foo&name=bar.

The QueryStringParameters field from the APIGatewayProxyRequest is defined as a map[string]string. This prevents doing things easily done with the standard http.request object. Example: Unmarshall URL query parameters using gorilla/schema (https://github.com/gorilla/schema)

The initial issue posted about this can be found here (https://github.com/aws/aws-lambda-go/issues/42)

A statement was made pointing out the limitation was on the APIGateway. This doesn't appear to be the case any longer.

https://aws.amazon.com/blogs/compute/support-for-multi-value-parameters-in-amazon-api-gateway/

**Comment by hinoguma** [comment]
#136 
The APIGatewayProxyRequest has MultiValueQueryStringParameters for multiple query params.
