### ISSUE TITLE
Support for Lambda Payload version 2.0

### ISSUE THREAD

**Issue by realharry** [aws/aws-lambda-go#273]
**Is your feature request related to a problem? Please describe.**

AWS recently announced GA for "HTTP API" for API Gateway, which supports a newer JSON format for Lambda Payload. It'll be nice if we can use aws-lambda-go with HTTP API/Lamda payload format 2.0.

**Describe the solution you'd like**

An optional flag to use version 2 vs version 1 formats.

**Describe alternatives you've considered**

N/A

**Additional context**

Relevant blog post: https://aws.amazon.com/blogs/compute/building-better-apis-http-apis-now-generally-available/

**Comment by shashank-sachan** [comment]
+1
I was also looking for the new payload support like requestContext.routeKey and other key pairs.

**Comment by bmoffatt** [comment]
Implemented by #274
