### ISSUE TITLE
Nested event structure definitions cause downstream code generation problems

### ISSUE THREAD

**Issue by ewbankkit** [aws/aws-lambda-go#276]
**Is your feature request related to a problem? Please describe.**

[Rust event types for AWS Lambda](https://github.com/LegNeato/aws-lambda-events) are generated from this project's event definitions and the recent introduction of nested Go structure definitions in `APIGatewayV2HTTPRequestContext` via https://github.com/aws/aws-lambda-go/pull/274 has caused Rust code generation to fail (Rust has no nested structure definitions).

**Describe the solution you'd like**
Would it be possible to declare all event types as top-level structures?

**Describe alternatives you've considered**
In the short term a blacklist for structures that can't be handled could be introduced but the long term alternative would be significant work to rejig the Rust code generator.

**Comment by bmoffatt** [comment]
> Would it be possible to declare all event types as top-level structures?

Seems fine to me
