### ISSUE TITLE
AppSync Support

### ISSUE THREAD

**Issue by benkraus** [aws/aws-lambda-go#28]
AppSync is currently in Preview, but it would be great to have support for AppSync Lambda Resolvers here. [Here](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-reference-lambda.html) is the documentation.

The way I see it, is this library could support doing things as described in the docs - using `field` and `arguments` in the `payload`. It could support both `Invoke` and `BatchInvoke` operations, and therefore if using `BatchInvoke`, it would need to handle maintaining the order of the items sent in, etc.

Thoughts? I'd be willing to help out getting this done.

**Comment by bmoffatt** [comment]
Having a helper that handles both `Invoke` and `BatchInvoke` would be useful! However, i'd hold off on adding support to this repo until AppSync has left preview.
