### ISSUE TITLE
Message visibility timeout

### ISSUE THREAD

**Issue by bradleyjames** [aws/aws-lambda-go#289]
**Is your feature request related to a problem? Please describe.**

From what I can tell the result of the lambda is either success or failure.  We'd like to use a message's visibility in order to retry a message after its timeout.  The only way I see to achieve similar functionality today is if the lambda were to add the message back to the queue.  The problem with that is the message goes to the back of the line.  It will now be subject to the queue's delay configuration as it will process messages already in the queue first.

**Describe the solution you'd like**

Provide a way to specify a message should not be acknowledged after processing so that it reappears in the queue after its visibility timeout.

**Describe alternatives you've considered**

As mentioned above we could add the message back to the queue but it will delay its processing based on the number of messages enqueued.

**Additional context**

We'd like to use this in order to throttle executions of CodeBuild builds.  We need to ensure only a limited number of builds are being performed at a time.  When under heavy load, or if a dependency is having issues, we will need to throttle the number of concurrent builds.  We're essentially wanting to wait until an execution slot is available or get as close to possible to that idea.  Lambda concurrent message configuration doesn't help as the lambda will only be executing for the duration of the start build request and not the full build.

**Comment by bmoffatt** [comment]
You might look into using a [dead-letter-queue, or another Lambda Function](https://docs.aws.amazon.com/lambda/latest/dg/invocation-async.html#invocation-async-destinations), to receive the events that you return failures for. Be aware that Lambda also has a [configurable retry](https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-supports-max-retry-attempts-event-age-asynchronous-invocations/) mechanism built-in for asynchronous events.

I'm closing this issue, as it is not unique to the Go runtime. You might try reaching out to customer support, or posting on the AWS forums, about the problem you're trying to solve.
