### ISSUE TITLE
null scopes in ApiGatewayV2httpRequestContextAuthorizerJwtDescription

### ISSUE THREAD

**Issue by mattrjacobs** [aws/aws-lambda-go#317]
**Is your feature request related to a problem? Please describe.**
I am working on switching the payload type from 1.0 to 2.0 for an HTTP API I'm working on. When I did that with a stock Cognito JWT authorizer, I started receiving `"scopes": null` from my API Gateway.  The current definition is : 
```
type APIGatewayV2HTTPRequestContextAuthorizerJWTDescription struct {
	Claims map[string]string `json:"claims"`
        Scopes []string          `json:"scopes"`
}
```

This appears to be a common input from API Gateway -> Lambda, as seen in these examples:
* https://www.jeremydaly.com/verifying-self-signed-jwt-tokens-with-aws-http-apis/
* https://dev.to/martzcodes/token-authorizers-with-apigatewayv2-tricks-apigwv1-doesn-t-want-you-to-know-41jn

**Describe the solution you'd like**
I believe the `Scopes` field should be nullable

**Describe alternatives you've considered**

**Additional context**

**Comment by bmoffatt** [comment]
resolved by #320
