### ISSUE TITLE
Way to execute code on shutdown?

### ISSUE THREAD

**Issue by mikeparker** [aws/aws-lambda-go#318]
I want to maintain an event metrics client across multiple lambda invocations so the server does not get spammed. However, I need to be able to flush the queue on shutdown.

Does the AWS go lib have any way to execute code on shutdown? If I simply add code to the end of `main` (after the `lambda.Start`), or using `defer`, will it get executed?

From viewing the code it looks like the main method will finish if there is a runtime error, but I'm unsure what happens if the lambda gets shutdown - I could not see code for dealing with a shutdown message (I dont think it gets a `SIGTERM`?)

**Comment by jlordiales** [comment]
Same question, very similar use case. I initially just put the flush call on a `defer` from the handler function but that's obviously not ideal.
cc @bmoffatt

**Comment by jlordiales** [comment]
I tried something like this today to see if the signal was being sent to the container but it didn't work either:
```go
done := make(chan struct{})
go func() {
  log.Println("Listening for signals...")
  c := make(chan os.Signal, 1)
  signal.Notify(c, os.Interrupt, syscall.SIGTERM)

  <-c
  close(done)
}()

go lambda.Start(HandleRequest)

<-done
log.Println("shutting down")
```

The lambda still works fine and I can see the "Listening for signals" log entry in CloudWatch but never the "shutting down" one

**Comment by bmoffatt** [comment]
Today, teardown of functions happens with SIGKILL. We're aware of other asks for a shutdown signal (like SIGTERM), and I've passed this issue along to the product team for reference.

**Comment by skiarn** [comment]
Hello, what is the recommended way to achieve same result? Since os/signal cannot be used to catch SIGKILL`The signals SIGKILL and SIGSTOP may not be caught by a program, and therefore cannot be affected by this package.` read more here: https://golang.org/pkg/os/signal

**Comment by ianic** [comment]
I made few experiments and observe two different behaviors. 
First is explained in this thread; there is no way to get SIGTERM and that is true for Lambda functions without extensions. But if you register an external extensions for a Lambda function than functions gets SIGTERM and has 500 ms to do useful work. It is killed after that timeout. 

I first observe it when playing with [extensions](https://github.com/aws-samples/aws-lambda-extensions/issues/63). 
Then I repeat the same with the Go code. Make s dummy Go Lambda function: 
``` Go
type MyEvent struct {
	Name string `json:"name"`
}

func HandleRequest(ctx context.Context, name MyEvent) (string, error) {
	return fmt.Sprintf("Hello %s!", name.Name), nil
}

func main() {
	sigs := make(chan os.Signal, 1)
	signal.Notify(sigs, syscall.SIGTERM, syscall.SIGINT)
	go func() {
		log.Printf("waiting for the SIGTERM ")
		s := <-sigs
		log.Printf("received signal %s", s)
		time.Sleep(500 * time.Millisecond)
		log.Printf("done")
	}()

	lambda.Start(HandleRequest)
}
```
There is no way to see `received signal` log line. 

But when I add simple extensions built from [this](https://github.com/aws-samples/aws-lambda-extensions/tree/main/go-example-extension) example there is both `received` and `done` lines in the log. 

<img width="1279" alt="Screenshot 2022-01-22 at 18 42 23" src="https://user-images.githubusercontent.com/35909/150649620-bb1d13e3-c5b7-4794-98ce-a9669eec2a2b.png">

**Comment by bmoffatt** [comment]
https://github.com/aws/aws-lambda-go/releases/tag/v1.34.0 adds an `WithEnableSIGTERM` option that you can use to... enable SIGTERM, without also having to attach an extension layer.

docs w/ example: https://pkg.go.dev/github.com/aws/aws-lambda-go/lambda#WithEnableSIGTERM

**Comment by advanderveer** [comment]
Sorry for using this issue for help but I couldn't think of another place to ask this. Basically I'm not seeing any effect of enabling the option. My code looks like this:
```
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/aws/aws-lambda-go/lambda"
)

func HandleRequest(ctx context.Context, name map[string]any) error {
	deadline, _ := ctx.Deadline()
	fmt.Printf("Event: %+v Deadline: %v %s\n", name, deadline, time.Until(deadline))
	<-time.After(time.Until(deadline) + time.Second*3)
	return nil
}

func main() {
	sigs := make(chan os.Signal, 1)
	signal.Notify(sigs, syscall.SIGTERM, syscall.SIGINT)
	go func() {
		log.Printf("waiting for the SIGTERM ")
		s := <-sigs
		log.Printf("received signal %s", s)
		time.Sleep(300 * time.Millisecond)
		log.Printf("done")
	}()

	lambda.StartWithOptions(HandleRequest, lambda.WithEnableSIGTERM(func() {
		fmt.Println("Shutdown!")
	}))
}
```

And my lambda cloudformation looks like this (excluding logs, roles etc):
```yaml
  AdminUiLambda:
    Type: AWS::Lambda::Function
    DependsOn:
      - AdminUiLambdaLogs
    Properties:
      FunctionName: !Sub ${AWS::StackName}-AdminUiLambda
      PackageType: Zip
      Handler: main
      Runtime: go1.x
      Code: ../lambda/adminui/cmd/pkg.zip
      Role: !GetAtt AdminUiLambdaRole.Arn
      Timeout: 5
      MemorySize: 128
      ReservedConcurrentExecutions: 5
```

I'm expecting to see either "received signal" or "Shutdown!" but neither show up in logs? Or is this supposes to happen after 60minutes plus? I was expecting the SIGTERM to arrive at the lambda timeout of 5s. 

If I remove the blocking `<-time.After(time.Until(deadline) + time.Second*3)`  the sigterm also never shows up?

**Comment by ishworg** [comment]
> I'm expecting to see either "received signal" or "Shutdown!" but neither show up in logs? Or is this supposes to happen after 60minutes plus? I was expecting the SIGTERM to arrive at the lambda timeout of 5s.

> If I remove the blocking <-time.After(time.Until(deadline) + time.Second*3) the sigterm also never shows up?

It has already been 4 months and counting. I am extremely extremely keen to hear what the AWS team has to say on this. I have a almost scenario repro code with me that looks likes yours.

**Comment by ishworg** [comment]
@bmoffatt Please consider re-opening this thread. If there are enough folks out there with this bug, it _might_ very well likely be a _bug_ (if it quacks ...)

**Comment by bmoffatt** [comment]
@ishworg, @advanderveer, you might try changing the runtime from `go1.x` to `provided.al2`! 

Longer version:

The `go1.x` runtime has its log sink hooked up in a different way than the newer `provided`/`provided.al2` runtimes. There's an extra process in the middle that stderr/stdout is flowing through, which is resulting in the 500ms before the SIGKILL *usually* not being enough time for the logs to flush out to CloudWatch.

However, there are other ways to verify that the sigterm handler is actually running. Here's my code, where I use the `/tmp` directory to persist state across the process restart after timeout.

```
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/aws/aws-lambda-go/lambda"
)

func main() {
	lambda.StartWithOptions(
		func(ctx context.Context) error {
			deadline, _ := ctx.Deadline()
			log.Printf("Deadline: %v %s\n", deadline, time.Until(deadline))

			if shutdownTime, err := os.ReadFile("/tmp/shutdown"); err != nil {
				log.Print("no shutdown file found: ", err)
			} else {
				log.Print("previous shutdown recorded at: ", string(shutdownTime))
			}

			<-time.After(time.Until(deadline) + time.Second*3)
			return nil
		},
		lambda.WithEnableSIGTERM(func() {
			log.Print("Shutdown!")
			f, _ := os.Create("/tmp/shutdown")
			defer f.Close()
			fmt.Fprint(f, time.Now())
		}),
	)
}
```

The logs when the runtime is `provided.al2` look like this (notice, the `log.Print("Shutdown!")` output appears as expected):

```
2023/03/11/[$LATEST]286174c46b144632896efdf377e22f51 2023-03-11T23:15:33.701000 INIT_START Runtime Version: provided:al2.v16	Runtime Version ARN: arn:aws:lambda:us-west-2::runtime:a877059c39f5d33441dc2aac00a8beba450c75fa8d69c4c71e7de2cca4659967
2023/03/11/[$LATEST]286174c46b144632896efdf377e22f51 2023-03-11T23:15:33.762000 EXTENSION	Name: GoLangEnableSIGTERM	State: Ready	Events: []
2023/03/11/[$LATEST]286174c46b144632896efdf377e22f51 2023-03-11T23:15:33.763000 START RequestId: f3ceb37f-42b3-4c69-9c5f-4ca8fdd4571c Version: $LATEST
2023/03/11/[$LATEST]286174c46b144632896efdf377e22f51 2023-03-11T23:15:33.764000 2023/03/11 23:15:33 Deadline: 2023-03-11 23:15:38.763 +0000 UTC 4.998826215s
2023/03/11/[$LATEST]286174c46b144632896efdf377e22f51 2023-03-11T23:15:33.764000 2023/03/11 23:15:33 no shutdown file found: open /tmp/shutdown: no such file or directory
2023/03/11/[$LATEST]286174c46b144632896efdf377e22f51 2023-03-11T23:15:38.769000 2023/03/11 23:15:38 Shutdown!
2023/03/11/[$LATEST]286174c46b144632896efdf377e22f51 2023-03-11T23:15:39.371000 2023-03-11T23:15:39.371Z f3ceb37f-42b3-4c69-9c5f-4ca8fdd4571c Task timed out after 5.61 seconds
2023/03/11/[$LATEST]286174c46b144632896efdf377e22f51 2023-03-11T23:15:39.371000 END RequestId: f3ceb37f-42b3-4c69-9c5f-4ca8fdd4571c
2023/03/11/[$LATEST]286174c46b144632896efdf377e22f51 2023-03-11T23:15:39.371000 REPORT RequestId: f3ceb37f-42b3-4c69-9c5f-4ca8fdd4571c	Duration: 5607.35 ms	Billed Duration: 5670 ms	Memory Size: 128 MB	Max Memory Used: 19 MB	Init Duration: 62.32 ms
2023/03/11/[$LATEST]286174c46b144632896efdf377e22f51 2023-03-11T23:15:45.319000 EXTENSION	Name: GoLangEnableSIGTERM	State: Ready	Events: []
2023/03/11/[$LATEST]286174c46b144632896efdf377e22f51 2023-03-11T23:15:45.319000 START RequestId: 8e7009c0-c50d-47b0-b00d-fb6d4ad7be76 Version: $LATEST
2023/03/11/[$LATEST]286174c46b144632896efdf377e22f51 2023-03-11T23:15:45.319000 2023/03/11 23:15:45 Deadline: 2023-03-11 23:15:49.484 +0000 UTC 4.164061621s
2023/03/11/[$LATEST]286174c46b144632896efdf377e22f51 2023-03-11T23:15:45.339000 2023/03/11 23:15:45 previous shutdown recorded at: 2023-03-11 23:15:38.769601947 +0000 UTC m=+5.039677413
2023/03/11/[$LATEST]286174c46b144632896efdf377e22f51 2023-03-11T23:15:49.485000 2023/03/11 23:15:49 Shutdown!
2023/03/11/[$LATEST]286174c46b144632896efdf377e22f51 2023-03-11T23:15:50.086000 2023-03-11T23:15:50.086Z 8e7009c0-c50d-47b0-b00d-fb6d4ad7be76 Task timed out after 5.60 seconds
2023/03/11/[$LATEST]286174c46b144632896efdf377e22f51 2023-03-11T23:15:50.086000 END RequestId: 8e7009c0-c50d-47b0-b00d-fb6d4ad7be76
2023/03/11/[$LATEST]286174c46b144632896efdf377e22f51 2023-03-11T23:15:50.086000 REPORT RequestId: 8e7009c0-c50d-47b0-b00d-fb6d4ad7be76	Duration: 5602.29 ms	Billed Duration: 5000 ms	Memory Size: 128 MB	Max Memory Used: 13 MB
```


and the logs then the runtime is `go1.x` look like this (notice, the `log.Printf("Shutdown!")` output is unfortunately missing, but the `/tmp/shutdown` file got written!):

```
2023/03/11/[$LATEST]cf7bd56d43d6416e896feff4fd29f9c4 2023-03-11T23:18:48.156000 INIT_START Runtime Version: go:1.v15	Runtime Version ARN: arn:aws:lambda:us-west-2::runtime:cb7b67d90cfa2cac75319b603ddfe27dfd4a3e64d830ef7ba99a87d7d5a55ce1
2023/03/11/[$LATEST]cf7bd56d43d6416e896feff4fd29f9c4 2023-03-11T23:18:48.253000 EXTENSION	Name: GoLangEnableSIGTERM	State: Ready	Events: []
2023/03/11/[$LATEST]cf7bd56d43d6416e896feff4fd29f9c4 2023-03-11T23:18:48.254000 START RequestId: 0a5136b7-45b7-4f82-94fe-d4d95de39193 Version: $LATEST
2023/03/11/[$LATEST]cf7bd56d43d6416e896feff4fd29f9c4 2023-03-11T23:18:48.255000 2023/03/11 23:18:48 Deadline: 2023-03-11 23:18:53.253111529 +0000 UTC 4.997740989s
2023/03/11/[$LATEST]cf7bd56d43d6416e896feff4fd29f9c4 2023-03-11T23:18:48.255000 2023/03/11 23:18:48 no shutdown file found: open /tmp/shutdown: no such file or directory
2023/03/11/[$LATEST]cf7bd56d43d6416e896feff4fd29f9c4 2023-03-11T23:18:53.259000 2023-03-11T23:18:53.259Z 0a5136b7-45b7-4f82-94fe-d4d95de39193 Task timed out after 5.00 seconds
2023/03/11/[$LATEST]cf7bd56d43d6416e896feff4fd29f9c4 2023-03-11T23:18:53.259000 END RequestId: 0a5136b7-45b7-4f82-94fe-d4d95de39193
2023/03/11/[$LATEST]cf7bd56d43d6416e896feff4fd29f9c4 2023-03-11T23:18:53.259000 REPORT RequestId: 0a5136b7-45b7-4f82-94fe-d4d95de39193	Duration: 5004.38 ms	Billed Duration: 5000 ms	Memory Size: 128 MB	Max Memory Used: 30 MB	Init Duration: 97.82 ms
2023/03/11/[$LATEST]cf7bd56d43d6416e896feff4fd29f9c4 2023-03-11T23:18:59.647000 EXTENSION	Name: GoLangEnableSIGTERM	State: Ready	Events: []
2023/03/11/[$LATEST]cf7bd56d43d6416e896feff4fd29f9c4 2023-03-11T23:18:59.647000 START RequestId: 5e7a5516-fcae-45fe-b892-ce88688c97d5 Version: $LATEST
2023/03/11/[$LATEST]cf7bd56d43d6416e896feff4fd29f9c4 2023-03-11T23:18:59.648000 2023/03/11 23:18:59 Deadline: 2023-03-11 23:19:03.446625591 +0000 UTC 3.79860937s
2023/03/11/[$LATEST]cf7bd56d43d6416e896feff4fd29f9c4 2023-03-11T23:18:59.667000 2023/03/11 23:18:59 previous shutdown recorded at: 2023-03-11 23:18:53.25826704 +0000 UTC m=+5.054825341
2023/03/11/[$LATEST]cf7bd56d43d6416e896feff4fd29f9c4 2023-03-11T23:19:03.448000 2023-03-11T23:19:03.448Z 5e7a5516-fcae-45fe-b892-ce88688c97d5 Task timed out after 5.00 seconds
2023/03/11/[$LATEST]cf7bd56d43d6416e896feff4fd29f9c4 2023-03-11T23:19:03.448000 END RequestId: 5e7a5516-fcae-45fe-b892-ce88688c97d5
2023/03/11/[$LATEST]cf7bd56d43d6416e896feff4fd29f9c4 2023-03-11T23:19:03.448000 REPORT RequestId: 5e7a5516-fcae-45fe-b892-ce88688c97d5	Duration: 5001.83 ms	Billed Duration: 5000 ms	Memory Size: 128 MB	Max Memory Used: 15 MB
```

**Comment by ishworg** [comment]
@bmoffatt thank you for your prompt response.

I should have mentioned that we are already use `provided/al.2` and still seeing this behavior. happy to provide any lambda config or repro code if you want.

**Comment by advanderveer** [comment]
For me, changing to the "provided.al2" solved my issue

**Comment by rdumont** [comment]
At first I went through the same issue before realizing that the callback in `lambda.WithEnableSIGTERM` is non-blocking. So use your own `done := make(chan struct{})` to ensure that the function doesn't exit before your callback is done doing whatever it has to do. Then the SIGTERM worked perfectly with `provided.al2`.
