### ISSUE TITLE
Add support for API Gateway HTTP API custom authorizers

### ISSUE THREAD

**Issue by ewbankkit** [aws/aws-lambda-go#321]
**Is your feature request related to a problem? Please describe.**
API Gateway HTTP APIs now supports Lambda authorization options.
Add `V2` structures corresponding to the existing `APIGatewayCustomAuthorizer` structures in `events/apigw.go`.

Announcement: https://aws.amazon.com/about-aws/whats-new/2020/09/api-gateway-http-apis-now-supports-lambda-and-iam-authorization-options/.
Request and response payload formats: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html.

**Comment by bmoffatt** [comment]
implemented by #328
