### ISSUE TITLE
Fix KafkaRecord struct

### ISSUE THREAD

**Issue by shlomi-ozon** [aws/aws-lambda-go#349]
Hello,
I have an issue with the KafkaRecord, my problem is that kafkaRecord contains Value from type String while I think it needs to be from the type []byte like KinesisRecord data.
Currently, I can't find any way to use KafkaRecord and parse the event value.
I also think that it will be very helpful if you will add a test for parsing the value data and not only the timestamp as the test does now.

thanks

**Comment by bmoffatt** [comment]
The field is base64 encoded ([ref](https://aws.amazon.com/blogs/compute/using-amazon-msk-as-an-event-source-for-aws-lambda/)). So you can use https://golang.org/pkg/encoding/base64/#Encoding.DecodeString
