### ISSUE TITLE
HTTP API (API Gateway v2) support for Payload Format v2.0

### ISSUE THREAD

**Issue by abelperezok** [aws/aws-lambda-go#369]
**Is your feature request related to a problem? Please describe.**

One of the possible integrations with Lambda is HTTP APIs  aka API Gateway v2, the event object representation is missing (or at least I couldn't find it). It should describe the Payload Format v2.0.  The lack of it makes it difficult to integrate with such event.  More information in [AWS doics](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html#2.0)

**Describe the solution you'd like**
A new struct similar to APIGatewayProxyRequest which is tailored to the Payload Format v2.0. An existing implementation has been released for .NET runtime using the name [APIGatewayHttpApiV2ProxyRequest](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.APIGatewayEvents/APIGatewayHttpApiV2ProxyRequest.cs) 

**Describe alternatives you've considered**
The alternative is to create my own struct or force to use Payload Format v1.0. It would be good to have the specific struct available as part of this package. 

**Additional context**
If this is something  that might be considered low priority or the team is too busy focusing on something more important, I'll be happy to prepare a pull request to fix this.

**Comment by redaLaanait** [comment]
@abelperezok which version of the **aws-lambda-go** are you using? It seems that **API Gateway V2** is supported since v1.16.0:

[https://github.com/aws/aws-lambda-go/pull/274/files](https://github.com/aws/aws-lambda-go/pull/274/files)

**Comment by abelperezok** [comment]
@redaLaanait My mistake, I was using a much older version, 1.13. Thank you very much for pointing it out. I suspect the template that comes with AWS SAM CLI when running `sam init` needs some updates.
