### ISSUE TITLE
ISSUE: APIGatewayV2HTTPRequest is missing the RouteARN field which is important for authorizer

### ISSUE THREAD

**Issue by NilsRuettershoff** [aws/aws-lambda-go#394]
Dear Dev Team,

In a new project I use the API GW HTTP the first time. During implementation of the authorizer I noticed that, APIGatewayV2HTTPRequest in events/apigw.go has no field for "RouteARN" (which is the replacement for "methodARN" from V1). This is required to be able to respond with a policy as the ARN is required in the resource field.

As reference that this field exists, here the official documentation:
https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html

Please add the field to the event. THX :)

**Comment by bmoffatt** [comment]
I believe this was resolved by #399
