### ISSUE TITLE
Building for Windows

### ISSUE THREAD

**Issue by mattmatze** [aws/aws-lambda-go#40]
Might be helpful if you guys put in the readme that for Windows Developers you need to "set GOARCH=amd64" in addition to the "set GOOS=linux" command like this for cmd.exe.

set GOOS=linux
set GOARCH=amd64
go build -o main main.go
%USERPROFILE%\Go\bin\build-lambda-zip.exe -o main.zip main

**Comment by bmoffatt** [comment]
added with 68fa387
