### ISSUE TITLE
Wrong struct for IoTCustomAuthorizerRequest

### ISSUE THREAD

**Issue by rittneje** [aws/aws-lambda-go#400]
#67 intended to add the request/response structs for an IoT Core custom authorizer. However, the wrong documention was referenced, so the request structure is completely wrong. The correct structure is documented here: https://docs.aws.amazon.com/iot/latest/developerguide/config-custom-auth.html

Obviously fixing this is technically a breaking change, but I would think that should be acceptable all things considered.

cc @bmoffatt 

ETA: The response struct is also wrong.

**Comment by ynori7** [comment]
@rittneje I can update the models then. I just wonder if it would also make sense to raise a bug for whichever code base the test invoke tool is in because it doesn't seem very useful if you need to use different models for it.

**Comment by rittneje** [comment]
@ynori7 You could try to raise an issue against the SDK. https://github.com/aws/aws-sdk But really this is an issue with the TestInvokeAuthorizer feature from IoT Core, so you might want to raise a support ticket from your AWS account if possible.

**Comment by ynori7** [comment]
@rittneje @bmoffatt I opened a PR to correct it. Could you take a look?
