### ISSUE TITLE
APIGatewayProxyRequest  queryStringParameters does not support multiple parameter values

### ISSUE THREAD

**Issue by thoellrich** [aws/aws-lambda-go#42]
The URL in go's standard `http.Request` has a `Query()` accessor which returns a `map[string][]string` (see: https://github.com/golang/go/blob/master/src/net/url/url.go#L995). This allows one to send a request with `...&type=foo&type=bar...` and get both values using `http.Request.Query()["type"]`. 

The `QueryStringParameters` field from `APIGatewayProxyRequest` on the other hand is defined as a `map[string]string` (see: https://github.com/aws/aws-lambda-go/blob/master/events/apigw.go#L11). Supplying `...&type=foo&type=bar...` to a Lambda behind GatewayProxy only returns the last value for `type` - `bar` in this case.

A workaround is to supply the parameters as a list using a separator character as in: `...&type=foo,bar...`

**Comment by fsenart** [comment]
Hi @thoellrich 
This limitation comes from Amazon API Gateway, and this project only reflects this fact. You should ask for a feature request on the AWS forum.

**Comment by thoellrich** [comment]
Ok - will do. Thanks.

**Comment by brydavis** [comment]
Does anyone have a great example(s) for using query strings? Thanks
