### ISSUE TITLE
Create release

### ISSUE THREAD

**Issue by DanielBauman88** [aws/aws-lambda-go#453]
Hi there,
Is there a standard periodic release process for this package or are releases initiated manually by the maintainers?
I had a PR merged in https://github.com/aws/aws-lambda-go/issues/452 which I'd like to use. I see the last release was created 18 days ago.
Looking at the history it doesn't seem like there's a regular cadence, could you please create a release so that the above changes can be used?

**Comment by bmoffatt** [comment]
done! https://github.com/aws/aws-lambda-go/releases/tag/v1.33.0

**Comment by DanielBauman88** [comment]
Much appreciated.
