### ISSUE TITLE
DynamoDBAttributeValue) Integer() hides float conversion and truncation

### ISSUE THREAD

**Issue by amwill04** [aws/aws-lambda-go#454]
When converting `DynamoDBAttributeValue` using `Integer()` method it currently hides the conversion to `Float64` one is passed.

This hidden functionality hides its true nature and has led to errors downstream.

We are doing this as we are having to convert from a `DynamoDBAttributeValue` to `json` and therefore could be a `float` or an `int`

Example:
```golang
package main

import (
	"fmt"

	"github.com/aws/aws-lambda-go/events"
)

func main() {
	var val interface{}
	var err error
	// We may receive a float64 or an integer
	attr := events.NewNumberAttribute("0.123344")

	val, err = attr.Integer()
	if err != nil {
		// expect an error here but Integer() will return int64(float64) truncating the decimal
		// amd hiding the error.
		// we are therefore not able to correctly cast to float64
		val, err = attr.Float()
	}

	// To JSON - We are using a map as we are not sure what the key/values will be from the dynamodb stream
	output := map[string]interface{}{
		"key": val,
	}

	b, err := json.Marshal(output)
	if err != nil {
		panic(err)
	}

	fmt.Println(string(b))
	// Output: {"key":0}
}

```

It would seem more predictable behaviour for `Integer()` to return an error if `DynamoDBAttributeValue` is not of `integer` type.

**Comment by amwill04** [comment]
I should note: we could switch to use `Float()` upfront but this leads to issues with large `int64` values

**Comment by bmoffatt** [comment]
The `int64` returned by `Integer()` can't contain the largest DynamoDB Number either :) https://stackoverflow.com/a/53056505. If giant values or extreme precision matters, you may want to consider using `String()`, and the possibly the `math/big` library, to help fully preserve values downstream.

I'm also OK with an `Int64()`, that preserves the parse error, being added.

**Comment by amwill04** [comment]
@bmoffatt thanks - but either way the point being I can't use `Float()` to handle both `integers` and `floats`.

Im unsure what you mean `"that preserves the parse error"` - has the error if a `float` is passed it is not preserved. It is cast to an `int64` leading to truncation.

I suppose what I was expecting - and maybe it is me that's wrong here - that `Integer()` would behave the same as `strconv.ParseInt()` (which it uses) and return an `error`. If an end users was happy with truncating a `float` to `int` then they could explicitly do this rather it happening unbeknown.

**Comment by bmoffatt** [comment]
released in https://github.com/aws/aws-lambda-go/releases/tag/v1.34.0
