### ISSUE TITLE
Users unable to get get build-lambda-zip (Failed on MacOS, Windows 10 and 11)

### ISSUE THREAD

**Issue by duaneking** [aws/aws-lambda-go#463]
Windows users can not get build-lambda-zip

Repro Steps
On a clean win10 or win11 machine (this repos on both of mine) open an admin console:

go get -v -u github.com/aws/aws-lambda-go/cmd/build-lambda-zip

Actual Result: <no output from command, no binaries created in any directory>

No binaries get downloaded or build, nothing ends up in any of the bin directories.

**Comment by duaneking** [comment]
I have reproduced this on a brand new clean install of win11 as well as an older install of win10.

All attempts to get the tools needed to deploy simply fail with no error message or output of any kind.

No tools are added to any ./bin/ folder.

**Comment by duaneking** [comment]
>go.exe get -v -x -u github.com/aws/aws-lambda-go/cmd/build-lambda-zip
# get https://proxy.golang.org/github.com/@v/list
# get https://proxy.golang.org/github.com/aws/aws-lambda-go/cmd/@v/list
# get https://proxy.golang.org/github.com/aws/@v/list
# get https://proxy.golang.org/github.com/aws/aws-lambda-go/cmd/build-lambda-zip/@v/list
# get https://proxy.golang.org/github.com/aws/aws-lambda-go/@v/list
# get https://proxy.golang.org/github.com/@v/list: 404 Not Found (0.202s)
# get https://proxy.golang.org/github.com/aws/@v/list: 404 Not Found (0.202s)
# get https://proxy.golang.org/github.com/aws/aws-lambda-go/@v/list: 200 OK (0.208s)
# get https://proxy.golang.org/github.com/aws/aws-lambda-go/cmd/@v/list: 404 Not Found (1.752s)
# get https://proxy.golang.org/github.com/aws/aws-lambda-go/cmd/build-lambda-zip/@v/list: 404 Not Found (1.879s)

**Comment by duaneking** [comment]
Looks like dependencies are failing

**Comment by duaneking** [comment]
Its important to note that this is on a brand new install.

No prior versions of anything go related are on the system because its a new box.

**Comment by duaneking** [comment]
```

go.exe get -v -x -u github.com/aws/aws-lambda-go/cmd/build-lambda-zip
# get https://proxy.golang.org/github.com/jmespath/go-jmespath/@v/v0.4.0.mod
# get https://proxy.golang.org/github.com/aws/aws-sdk-go/@v/v1.44.80.mod
# get https://proxy.golang.org/github.com/aws/aws-lambda-go/@v/v1.34.1.mod
# get https://proxy.golang.org/github.com/aws/aws-sdk-go/@v/v1.44.80.mod: 200 OK (0.485s)
# get https://proxy.golang.org/github.com/jmespath/go-jmespath/@v/v0.4.0.mod: 200 OK (0.486s)
# get https://proxy.golang.org/golang.org/x/net/@v/v0.0.0-20220127200216-cd36cc0744dd.mod
# get https://proxy.golang.org/github.com/pkg/errors/@v/v0.9.1.mod
# get https://proxy.golang.org/github.com/jmespath/go-jmespath/internal/testify/@v/v1.5.1.mod
# get https://proxy.golang.org/github.com/aws/aws-lambda-go/@v/v1.34.1.mod: 200 OK (0.510s)
# get https://proxy.golang.org/github.com/pkg/errors/@v/v0.9.1.mod: 200 OK (0.140s)
# get https://proxy.golang.org/golang.org/x/net/@v/v0.0.0-20220127200216-cd36cc0744dd.mod: 200 OK (0.143s)
# get https://proxy.golang.org/github.com/jmespath/go-jmespath/internal/testify/@v/v1.5.1.mod: 200 OK (0.144s)
# get https://proxy.golang.org/golang.org/x/sys/@v/v0.0.0-20211216021012-1d35b9e2eb4e.mod
# get https://proxy.golang.org/golang.org/x/text/@v/v0.3.7.mod
# get https://proxy.golang.org/golang.org/x/term/@v/v0.0.0-20210927222741-03fcf44c2211.mod
# get https://proxy.golang.org/github.com/davecgh/go-spew/@v/v1.1.0.mod
# get https://proxy.golang.org/gopkg.in/yaml.v2/@v/v2.2.8.mod
# get https://proxy.golang.org/github.com/stretchr/objx/@v/v0.1.0.mod
# get https://proxy.golang.org/github.com/pmezard/go-difflib/@v/v1.0.0.mod
# get https://proxy.golang.org/github.com/stretchr/objx/@v/v0.1.0.mod: 200 OK (0.145s)
# get https://proxy.golang.org/gopkg.in/yaml.v2/@v/v2.2.8.mod: 200 OK (0.146s)
# get https://proxy.golang.org/github.com/davecgh/go-spew/@v/v1.1.0.mod: 200 OK (0.147s)
# get https://proxy.golang.org/golang.org/x/term/@v/v0.0.0-20210927222741-03fcf44c2211.mod: 200 OK (0.150s)
# get https://proxy.golang.org/golang.org/x/text/@v/v0.3.7.mod: 200 OK (0.150s)
# get https://proxy.golang.org/golang.org/x/sys/@v/v0.0.0-20211216021012-1d35b9e2eb4e.mod: 200 OK (0.153s)
# get https://proxy.golang.org/github.com/pmezard/go-difflib/@v/v1.0.0.mod: 200 OK (0.153s)
# get https://proxy.golang.org/gopkg.in/check.v1/@v/v0.0.0-20161208181325-20d25e280405.mod
# get https://proxy.golang.org/golang.org/x/tools/@v/v0.0.0-20180917221912-90fa682c2a6e.mod
# get https://proxy.golang.org/golang.org/x/sys/@v/v0.0.0-20210615035016-665e8c7367d1.mod
# get https://proxy.golang.org/gopkg.in/check.v1/@v/v0.0.0-20161208181325-20d25e280405.mod: 200 OK (0.143s)
# get https://proxy.golang.org/golang.org/x/sys/@v/v0.0.0-20210615035016-665e8c7367d1.mod: 200 OK (0.142s)
# get https://proxy.golang.org/golang.org/x/tools/@v/v0.0.0-20180917221912-90fa682c2a6e.mod: 200 OK (0.144s)
# get https://proxy.golang.org/github.com/aws/@v/list
# get https://proxy.golang.org/github.com/aws/aws-lambda-go/cmd/@v/list
# get https://proxy.golang.org/github.com/aws/aws-lambda-go/@v/list
# get https://proxy.golang.org/github.com/aws/aws-lambda-go/cmd/build-lambda-zip/@v/list
# get https://proxy.golang.org/github.com/@v/list
# get https://proxy.golang.org/github.com/aws/aws-lambda-go/@v/list: 200 OK (0.162s)
# get https://proxy.golang.org/github.com/aws/aws-lambda-go/@v/v1.34.1.info
# get https://proxy.golang.org/github.com/aws/@v/list: 404 Not Found (0.167s)
# get https://proxy.golang.org/github.com/@v/list: 404 Not Found (0.167s)
# get https://proxy.golang.org/github.com/aws/aws-lambda-go/@v/v1.34.1.info: 200 OK (0.148s)
go: downloading github.com/aws/aws-lambda-go v1.34.1
# get https://proxy.golang.org/github.com/aws/aws-lambda-go/@v/v1.34.1.zip
# get https://proxy.golang.org/github.com/aws/aws-lambda-go/@v/v1.34.1.zip: 200 OK (0.154s)
# get https://proxy.golang.org/github.com/aws/aws-lambda-go/cmd/@v/list: 404 Not Found (2.412s)
# get https://proxy.golang.org/github.com/aws/aws-lambda-go/cmd/build-lambda-zip/@v/list: 404 Not Found (2.412s)

```

**Comment by duaneking** [comment]
AWS must have moved stuff on GitHub and broken the download link?

**Comment by duaneking** [comment]
Respectfully tagging @calavera as I'm worried this is very broken and its actively blocking deployments from multiple different machines.

**Comment by duaneking** [comment]
I'm getting the same output on a MBP, so updating title.

**Comment by bmoffatt** [comment]
What version of go are you using?

go 1.18 removed the ability to use `go get` to install binaries, and should log an error message point you to use `go install` instead - but, I can see now that this error isn't logged when the working directory contains a `go.mod` file, which perhaps describes your environment.

https://go.dev/doc/go1.18#go-command

**Comment by duaneking** [comment]
On:

Windows 11 and Windows 10:  go version -> go1.19 windows/amd64
OSX: go version -> go1.19 darwin/amd64

I'm just following the official readme; If the documentation needs updated that should be done as well.   It's great that some of us can have the privilege of shiny new Macbooks, but not everybody has that.

**Comment by shogo82148** [comment]
I created a pull request https://github.com/aws/aws-lambda-go/pull/464 fixing the README.

The developers document also should be fixed.

https://docs.aws.amazon.com/lambda/latest/dg/golang-package.html#golang-package-windows

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/1157344/185732996-d1fbe35a-f47d-4b21-bb0c-eebde8fd13f2.png">

**Comment by duaneking** [comment]
Docs also need amd64 verses arm64 clarification.

**Comment by duaneking** [comment]
I can file a separate bug for that if needed, let me know.

Imagine the adoption that this has stopped.  Sounds like an expensive documentation bug.
