### ISSUE TITLE
CloudWatchEvent should be renamed

### ISSUE THREAD

**Issue by mostafafarzaneh** [aws/aws-lambda-go#479]
I think because the [documentation](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-what-is.html) suggests using EventBridge over CloudWatchEvent, I thought that it is better to rename CloudWatchEvent to something that includes EventBridge maybe?

**Comment by bmoffatt** [comment]
Maybe a type alias would do here. As far as I know the structure of these events hasn't changed, just the branding.
