### ISSUE TITLE
Support for AWS CodePipeline

### ISSUE THREAD

**Issue by brianterry** [aws/aws-lambda-go#48]
Hello, there are no events for AWS CodePipeline jobs.  This would be great to have.

**Comment by brianterry** [comment]
I have a PR open for this issue.  I was looking at the AWS docs, and noticed that their sample JSON includes "null".  https://docs.aws.amazon.com/codepipeline/latest/userguide/actions-invoke-lambda-function.html#actions-invoke-lambda-function-json-event-example  In the  unmarshal and marshal event, go converts this to " "

**Comment by bmoffatt** [comment]
merged #53
