### ISSUE TITLE
Is it possible to invoke a Go Lambda via RPC?

### ISSUE THREAD

**Issue by yosriady** [aws/aws-lambda-go#49]
I'm wondering if it's possible to invoke a Go Lambda via RPC (instead of HTTP via API Gateway)?

Internally, it seems this library uses `net/rpc` here: https://github.com/aws/aws-lambda-go/blob/master/lambda/entry.go#L8

**Comment by mlctrez** [comment]
@yosriady  Yes that is possible.

The invoke method signature is defined at:
https://github.com/aws/aws-lambda-go/blob/64efb26269cc5d9c363a143a936a7c75b053e06d/lambda/function.go#L24

* Server

```
package main

import (
	"os"

	"github.com/aws/aws-lambda-go/lambda"
)

func hello() (string, error) {
	return "Hello λ!", nil
}

func main() {

	// the _LAMBDA_SERVER_PORT environment would normally be provided externally
	os.Setenv("_LAMBDA_SERVER_PORT", "9988")

	lambda.Start(hello)

}

```


* Client
```
package main

import (
	"fmt"
	"log"
	"net/rpc"

	"github.com/aws/aws-lambda-go/lambda/messages"
)

func main() {
	c, err := rpc.Dial("tcp", "127.0.0.1:9988")
	if err != nil {
		log.Fatalln(err)
	}

	var result messages.InvokeResponse
	request := &messages.InvokeRequest{}
	err = c.Call("Function.Invoke", request, &result)

	if err != nil {
		log.Fatal(err)
	}
	if result.Error != nil {
		log.Fatal(result.Error.Message)
	}

	fmt.Println("Function.Invoke =", string(result.Payload))

}

```

**Comment by bmoffatt** [comment]
@yosriady I'm guessing you mean invoking the uploaded Lambda function?

You are not limited to using API Gateway to Invoke your Lambda Function. You may also the AWS SDK for Go (or any language) to invoke your lambda function directly. https://github.com/aws/aws-sdk-go https://docs.aws.amazon.com/sdk-for-go/api/service/lambda/#Lambda.Invoke

**Comment by yosriady** [comment]
@mlctrez 
How would `rpc.Dial("tcp", "127.0.0.1:9988")` work? Wouldn't you need to connect to the IP of the Lambda function?

**Comment by yosriady** [comment]
@bmoffatt 

Yes, I'd like to invoke my Lambda function via both HTTP and RPC if possible. 

I'm aware that we can invoke it using the AWS Lambda SDK.

**Comment by mlctrez** [comment]
@yosriady   
I read your question as wanting to test a go lambda binary locally. That was an incorrect assumption on my part. 

For a Lambda running on AWS, the RPC IP and Port are not accessible outside of the AWS Lambda infrastructure.

**Comment by bmoffatt** [comment]
To go with @mlctrez comments:

From https://aws.amazon.com/lambda/faqs/

> Q: What restrictions apply to AWS Lambda function code?
>
> Lambda attempts to impose as few restrictions as possible on normal language and operating system activities, but there are a few activities that are disabled: Inbound network connections are blocked by AWS Lambda, and for outbound connections only TCP/IP sockets are supported, and ptrace (debugging) system calls are blocked. TCP port 25 traffic is also blocked as an anti-spam measure.
