### ISSUE TITLE
Custom runtime provided.al2 broken on v1.42

### ISSUE THREAD

**Issue by BogdanDarius** [aws/aws-lambda-go#535]
When trying to invoke lambda function using the latest version v1.42 and custom runtime al2 I get the following error:
```json
Phase: invoke	Status: error	Error Type: Runtime.Unknown
```

**Comment by bmoffatt** [comment]
The service team is aware of an ongoing problem with the platform logs that may be related. 

https://repost.aws/questions/QUQW-ZJyV5SyKRi5iYTZVlUQ/why-am-i-seeing-runtime-unknown-in-the-init-report-log

If you're running into further issues, please open a support case!
