### ISSUE TITLE
LexEvent - ResponseCard error

### ISSUE THREAD

**Issue by iliasgal** [aws/aws-lambda-go#66]
I am not sure if this is a bug.

I am using a Lambda function as fulfilment to AWS Lex. I want to send a response using the code below:  

```
func scheduleMeeting(event events.LexEvent) (events.LexEvent, error) {

    //some code here

    response := events.LexEvent{
        DialogAction: &events.LexDialogAction{
            Type:             "Close",
            FulfillmentState: "Fulfilled",
            Message:          map[string]string{"contentType": "PlainText", "content": "Thank you!"},
        },
    }

    return response, nil
}
```
However, I am getting the following error:

> An error has occurred: Invalid Lambda Response: Received invalid response from Lambda: Can not deserialize value of type ContentType from String "": value not one of declared Enum instance names: http://application/vnd.amazonaws.card.generic at Source: {"sessionAttributes":null,"dialogAction":{"type":"Close","fulfillmentState":"Fulfilled","message":{"content":"Thank you!","contentType":"PlainText"},"intentName":"","slots":null,"slotToElicit":"","responseCard":{"version":0,"contentType":"","genericAttachments":null}}}; line: 1, column: 239

This `ContentType` field and the Enum `application/vnd.amazonaws.card.generic` are on the `ResponseCard` field, which is optional according to the [documentation](https://docs.aws.amazon.com/lex/latest/dg/lambda-input-response-format.html#using-lambda-response-format).

**Comment by asuresh8** [comment]
Hmm that is strange, and if you add the the `ContentType: application/vnd.amazonaws.card.generic` in the `ResponseCard` object does the error go away?

**Comment by iliasgal** [comment]
I added the `ResponseCard` object.

```
var buttons []map[string]string
buttons = append(buttons, map[string]string{"text": "test", "value": "test"})

var attachements []events.Attachment
attachements = append(attachements, events.Attachment{
	Title:    "test",
	SubTitle: "test subtitle",
        ImageURL: "https://testurl.com",
	Buttons:  buttons,
})

response := events.LexEvent{
	DialogAction: &events.LexDialogAction{
		Type:             "Close",
		FulfillmentState: "Fulfilled",
		Message:          map[string]string{"contentType": "PlainText", "content": message},
		ResponseCard: events.LexResponseCard{
			Version:            1,
			ContentType:        "application/vnd.amazonaws.card.generic",
			GenericAttachments: attachements,
		},
	},
}
```

And the new error is:

> An error has occurred: Invalid Lambda Response: Received invalid response from Lambda: Can not construct instance of GenericAttachment$Builder, problem: Image Url is not in range <1,2048> at [Source: {"sessionAttributes":null,"dialogAction":{"type":"Close","fulfillmentState":"Fulfilled","message":{"content":"Your meeting sdfsdf has been scheduled for 2018-04-05 11:00:00 +0000 UTC","contentType":"PlainText"},"intentName":"","slots":null,"slotToElicit":"","responseCard":{"version":1,"contentType":"application/vnd.amazonaws.card.generic","genericAttachments":[{"title":"test","subTitle":"test subtitle","imageUrl":"test url","attachmentLinkUrl":"","buttons":[{"text":"test","value":"test"}]}]}}}; line: 1, column: 494]

As you can see there is an Image URL field set.

**Comment by asuresh8** [comment]
It almost seems as if Lex is checking the parameters on their end. What if you change the ImageURL to an actually valid URL? ex https://a0.awsstatic.com/main/images/logos/aws_logo_smile_1200x630.png

**Comment by iliasgal** [comment]
I had to add ImageURL, AttachmentLinkURL and IntentName
```
var buttons []map[string]string
buttons = append(buttons, map[string]string{"text": "test", "value": "test"})

var attachements []events.Attachment
attachements = append(attachements, events.Attachment{
	Title:             "test",
	SubTitle:          "test subtitle",
	ImageURL:          "https://a0.awsstatic.com/main/images/logos/aws_logo_smile_1200x630.png",
	AttachmentLinkURL: "https://a0.awsstatic.com/main/images/logos/aws_logo_smile_1200x630.png",
	Buttons:           buttons,
})

response := events.LexEvent{
	DialogAction: &events.LexDialogAction{
		IntentName:       event.CurrentIntent.Name,
		Type:             "Close",
		FulfillmentState: "Fulfilled",
		Message:          map[string]string{"contentType": "PlainText", "content": message},
		ResponseCard: events.LexResponseCard{
			Version:            1,
			ContentType:        "application/vnd.amazonaws.card.generic",
			GenericAttachments: attachements,
		},
	},
}

return response, nil
```

And the new error:

> An error has occurred: Invalid Lambda Response: Received invalid response from Lambda: Unrecognized field "intentName" (class CloseDialogAction), not marked as ignorable at [Source: {"sessionAttributes":null,"dialogAction":{"type":"Close","fulfillmentState":"Fulfilled","message":{"content":"Your meeting AAA has been scheduled for 2018-04-05 11:00:00 +0000 UTC","contentType":"PlainText"},"intentName":"ScheduleMeeting","slots":null,"slotToElicit":"","responseCard":{"version":1,"contentType":"application/vnd.amazonaws.card.generic","genericAttachments":[{"title":"test","subTitle":"test subtitle","imageUrl":"https://a0.awsstatic.com/main/images/logos/aws_logo_smile_1200x630.png","attachmentLinkUrl":"https://a0.awsstatic.com/main/images/logos/aws_logo_smile_1200x630.png","buttons":[{"text":"test","value":"test"}]}]}}}; line: 1, column: 642]

I do not know what is wrong with intentName, but it is obvious that the LexEvent requires all fields to be populated, even those that make no sense to populate as response.

**Comment by asuresh8** [comment]
Yeah the error here is that we don't add omitEmpty to the json serialization of all of the struct fields

**Comment by 1pkt** [comment]
Hey !
Did you find any fix to this ? I got the same error, in the same context (I want to create an answer without any responseCard)

**Comment by bmoffatt** [comment]
Merged #75

**Comment by magicmoose** [comment]
Does this solve the problem for any of you? i still get 
```
An error has occurred: Invalid Lambda Response: Received invalid response from Lambda: Unrecognized field "responseCard" (class DelegateDialogAction), not marked as ignorable at [Source: {"dialogAction":{"type":"Delegate","slots":{"environment":""},"responseCard":{}}}; line: 1, column: 79]
```

**Comment by olivoil** [comment]
```

**Comment by MayankB11** [comment]
@magicmoose  Did you find the error?
