### ISSUE TITLE
Request: a way to pass a parent context into lambda.Start 

### ISSUE THREAD

**Issue by helloPiers** [aws/aws-lambda-go#7]
In porting a specimen Go lambda from a node.js "shim" based approach to this new native library, I find it's missing something from our shim-based library, which is a way to have a context.Context created in "main" made available in the handler function. 

Sometimes, for logging, or whatever, it's useful to adorn a context in the main function to be used as the parent context for all event handler invocations. 

One could use globals to pass context from main to the event handler, but that's not great for testing, etc.

Perhaps in addition to lambda.Start(handler) there could be lambda.StartWithContext(ctx, handler)? The passed in ctx could then be used in place of context.Background() in Function.Invoke.

**Comment by dlsniper** [comment]
There is no need for this, you should define your dependencies in a struct and have the handler on the struct as well. This allows you to decouple the code as well as reuse it in many different scenarios and it also allows you for better testing.

Context should be used to store request specific values which are passed to the functions that are executed during the life-cycle of the request. Anything else should be passed as a clear dependency, see below.

Please see the example here: https://play.golang.org/p/HfDKMbTfmFS

As such, I'm against doing such a change as it would encourage bad practices for Go.

Hope this helps.

```go
package main

import (
	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
)

type (
	Conf struct {
		Field string
	}

	Demo struct {
		conf Conf
	}
)

func (d *Demo) Handler(request events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
	return events.APIGatewayProxyResponse{
		Body:       "Hello " + d.conf.Field,
		StatusCode: 200,
	}, nil
}

func main() {
	conf := Conf{
		Field: "field",
	}
	demo := Demo{
		conf: conf,
	}
	lambda.Start(demo.Handler)
}
```

**Comment by helloPiers** [comment]
Yeah, no, fair enough it's probably not generally useful enough to be a feature of this library. It would just help porting various existing code that's using a context-based logging library that doesn't log with an unadorned context. Probably that's not an ideal pattern either. Worst case I can fork the library. There are other places like http server that create brand new contexts from from context.Background deep inside a library - that always feels a bit weird to me.
