### ISSUE TITLE
Returning error results in 502 from APIG

### ISSUE THREAD

**Issue by dgoradia** [aws/aws-lambda-go#72]
When the returned error value in not nil, the response results in a 502 error from API Gateway. 
e.g. 
```
func Handler(ctx context.Context, request events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
    ...
    // some error occured
    err := errors.New("something bad happened")
    return events.APIGatewayProxyResponse{
	StatusCode: 400,
	Body:       "",
    }, err
}
```

This results in a 502 Bad Gateway with response:
```
{
    "message": "Internal server error"
}
```

And when using the test functionality in API Gateway:
```
... Execution failed due to configuration error: Malformed Lambda proxy response
Fri Apr 13 18:05:24 UTC 2018 : Method completed with status: 502
```

**Comment by asuresh8** [comment]
This is expected behavior

**Comment by dgoradia** [comment]
Thanks, that's helpful. Can you provider an example of what a correct error response would look like?

**Comment by deluan** [comment]
It is to signal Lambda that your function got an unexpected error, hence the status code 502 returned by API Gateway. But ideally you want to handle all kinds of errors (including panics), and always return a proper http status code.

**Comment by sgarcez** [comment]
FWIW we've recently done some work around this and ended up using the custom (non proxy) integration. Here's some example code and a go test helper that uses sam local, in case it's of any use:
https://github.com/smalleats/serverless-todo-example
