### ISSUE TITLE
Can't update/delete custom resource: Invalid PhysicalResourceId

### ISSUE THREAD

**Issue by mansinahar** [aws/aws-lambda-go#77]
Hey there!

I have a lambda function that looks up a SSM parameter and returns it's value. This lambda function is triggered from a CloudFormation template by creating a custom resource. The CF stack launches correctly and works as expected although when I try to update or delete the stack, it fails saying "Invalid PhysicalResourceId".

I believe that the PhysicalResourceID in this block: https://github.com/aws/aws-lambda-go/blob/master/cfn/wrap.go#L33 should be set to the logStreamName (default PhysicalResourceID) if it is empty, no matter the request type. For now, I was able to get around with this by always setting the  PhysicalResourceID in my Lambda function to the logStreamName.

[#76] implements the suggested change. I tested this and with this change update and delete actions work as expected.

**Comment by bmoffatt** [comment]
Always setting the ID as the log stream name matches the behavior of the python and node helper libraries. Merged #76 Thanks for the PR!

**Comment by mansinahar** [comment]
@bmoffatt Thanks so much!
