### ISSUE TITLE
Problem With S3 Event

### ISSUE THREAD

**Issue by toneill818** [aws/aws-lambda-go#82]
The S3Object struct has URLDecodedKey but it does not seem to be populated when processing request. Looking at the [example](https://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html) event message structure this is not returned. The Key field is populated but spaces in filenames are replace with a '+'. Is this the expected behavior?

**Comment by oyi812** [comment]
Shoddy. Key should be the unencoded value. There should be an implemented field (looking at you AWS lambda devs) called URLEncodedKey. I'm certain this has caused problems for a fair number of users. It should have been fixed long ago.

**Comment by ARolek** [comment]
I just hit this problem as well. Unfortunate bug.

**Comment by estahn** [comment]
I'm facing the same issue.

**Comment by mkozjak** [comment]
I just hit the same issue. Might be related to Object ACL settings?

**Comment by vsomayaji** [comment]
The URL-decoded value is not included in the event. The SDK should be setting `URLDecodedKey` similar to how the Java SDK does it:

https://github.com/aws/aws-sdk-java/blob/6a4c873c71320ef0175ca1c13188e9c850a85e51/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/event/S3EventNotification.java#L176-L183

Until it does, you could set it yourself using something like this:

```go
	key, _ := url.QueryUnescape(record.S3.Object.Key)
	record.S3.Object.URLDecodedKey = key
```
