### ISSUE TITLE
events.S3Event range

### ISSUE THREAD

**Issue by bantl23** [aws/aws-lambda-go#86]
I was looking at the S3 Lambda example and I noticed that the records is a range: `for _, record := range s3Event.Records {...}`

I thought the Lambda events spawned a new process per event so I was wondering why there is a loop at all?

When can the handler receive multiple records? Is that possible? If so what would be the use case?

**Comment by bmoffatt** [comment]
The data model was designed to be future proof to support multiple records per event. https://forums.aws.amazon.com/thread.jspa?messageID=592264#592264, and also for structural consistency with similar event sources that do support multiple records, like Kinesis.
